# Generated by Django 4.2.3 on 2024-11-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('regex', models.CharField(help_text='Regular expression used for pattern matching.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the pattern.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScannedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('message_text', models.TextField(help_text='Original content of the message.')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_messages', to='leak_shield.pattern')),
            ],
            options={
                'verbose_name': 'Scanned Message',
                'verbose_name_plural': 'Scanned Messages',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_content', models.TextField(help_text='Extracted text content from the file for pattern analysis.')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_files', to='leak_shield.pattern')),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('BLOCK', 'Message Blocked'), ('REPLACE', 'Message Replaced'), ('ALERT', 'Alert Sent')], max_length=20)),
                ('action_details', models.TextField(help_text='Additional details about the action taken.')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='leak_shield.scannedfile')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='leak_shield.scannedmessage')),
            ],
        ),
    ]
